import { StyleSheet } from 'react-native';
import { AuthColors } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: AuthColors.background,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: AuthColors.text,
    letterSpacing: -0.5,
  },
  section: {
    marginBottom: 10,
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: AuthColors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    paddingHorizontal: 20,
    paddingBottom: 8,
    paddingTop: 16,
  },
  card: {
    backgroundColor: AuthColors.white,
    marginHorizontal: 16,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  profileCard: {
    backgroundColor: AuthColors.white,
    marginHorizontal: 16,
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: AuthColors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: 22,
    fontWeight: '700',
    color: AuthColors.white,
  },
  profileName: {
    fontSize: 17,
    fontWeight: '700',
    color: AuthColors.text,
  },
  profileSub: {
    fontSize: 13,
    color: AuthColors.textSecondary,
    marginTop: 2,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: AuthColors.border,
  },
  rowLast: {
    borderBottomWidth: 0,
  },
  rowIcon: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  rowLabel: {
    flex: 1,
    fontSize: 15,
    color: AuthColors.text,
    fontWeight: '500',
  },
  rowValue: {
    fontSize: 14,
    color: AuthColors.textSecondary,
    marginRight: 6,
  },
  chevron: {
    fontSize: 16,
    color: AuthColors.border,
    fontWeight: '600',
  },
  providerBadge: {
    backgroundColor: AuthColors.primary,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  providerBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: AuthColors.white,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  providerDetailCard: {
    backgroundColor: AuthColors.white,
    marginHorizontal: 16,
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  providerDetailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  providerDetailTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: AuthColors.text,
  },
  providerDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
    borderTopWidth: 1,
    borderTopColor: AuthColors.border,
  },
  providerDetailLabel: {
    fontSize: 13,
    color: AuthColors.textSecondary,
  },
  providerDetailValue: {
    fontSize: 13,
    fontWeight: '600',
    color: AuthColors.text,
  },
  dangerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  dangerIcon: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: '#FEE2E2',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  dangerLabel: {
    fontSize: 15,
    color: '#DC2626',
    fontWeight: '500',
  },
});
