import { StyleSheet } from 'react-native';
import { AuthColors } from '@/constants/theme';

export const transportSearchStyles = StyleSheet.create({
  card: {
    backgroundColor: AuthColors.white,
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginTop: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: AuthColors.text,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
  },
  titleRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 14 },
  titleText: { fontSize: 16, fontWeight: '700', color: AuthColors.text },

  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#F9FAFB',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: AuthColors.border,
    paddingHorizontal: 12,
    paddingVertical: 11,
    marginBottom: 10,
  },
  inputText: { flex: 1, fontSize: 14, color: AuthColors.text },
  inputPlaceholder: { flex: 1, fontSize: 14, color: AuthColors.placeholder },
  dividerDots: { alignItems: 'center', marginVertical: 2, marginLeft: 6 },
  dot: { width: 4, height: 4, borderRadius: 2, backgroundColor: AuthColors.border, marginVertical: 1 },
  searchBtn: {
    backgroundColor: AuthColors.primary,
    borderRadius: 12,
    paddingVertical: 13,
    alignItems: 'center',
    marginTop: 4,
  },
  searchBtnText: { color: '#fff', fontWeight: '700', fontSize: 15 },
  locationLoading: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  locationLoadingText: { fontSize: 12, color: AuthColors.textSecondary },
});

export const transportResultStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: AuthColors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: AuthColors.white,
    borderBottomWidth: 1,
    borderBottomColor: AuthColors.border,
  },
  backButton: { padding: 4, marginRight: 8 },
  backText: { fontSize: 28, color: AuthColors.primary, lineHeight: 32 },
  headerTitle: { fontSize: 18, fontWeight: '700', color: AuthColors.text },
  radiusInfo: {
    fontSize: 12,
    color: AuthColors.textSecondary,
    textAlign: 'center',
    marginVertical: 12,
    paddingHorizontal: 16,
  },
  loadingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 },
  loadingText: { fontSize: 14, color: AuthColors.textSecondary },
  emptyContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 32 },
  emptyText: { fontSize: 16, color: AuthColors.textSecondary, textAlign: 'center', marginTop: 16 },
  list: { paddingHorizontal: 16, paddingBottom: 32 },
  providerCard: {
    backgroundColor: AuthColors.white,
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  providerHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 10 },
  providerPhoto: { width: 52, height: 52, borderRadius: 26, backgroundColor: '#E5E7EB', overflow: 'hidden', alignItems: 'center', justifyContent: 'center' },
  providerPhotoImg: { width: 52, height: 52, borderRadius: 26 },
  providerInfo: { flex: 1 },
  providerName: { fontSize: 16, fontWeight: '700', color: AuthColors.text },
  providerSub: { fontSize: 13, color: AuthColors.textSecondary, marginTop: 2 },
  distanceBadge: {
    backgroundColor: '#EFF6FF',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  distanceText: { fontSize: 12, color: '#1D4ED8', fontWeight: '600' },
  chipSection: { marginBottom: 8 },
  chipLabel: { fontSize: 12, color: AuthColors.textSecondary, marginBottom: 4, fontWeight: '600' },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  chip: { backgroundColor: '#F3F4F6', borderRadius: 12, paddingHorizontal: 10, paddingVertical: 4 },
  chipText: { fontSize: 12, color: AuthColors.text },
  callBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: AuthColors.primary,
    borderRadius: 10,
    paddingVertical: 10,
    marginTop: 10,
  },
  callBtnText: { color: '#fff', fontWeight: '700', fontSize: 14 },
});

export const destinationPickerStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: AuthColors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: AuthColors.white,
    borderBottomWidth: 1,
    borderBottomColor: AuthColors.border,
  },
  backButton: { padding: 4, marginRight: 8 },
  backText: { fontSize: 28, color: AuthColors.primary, lineHeight: 32 },
  headerTitle: { fontSize: 18, fontWeight: '700', color: AuthColors.text },
  breadcrumb: { fontSize: 12, color: AuthColors.textSecondary, marginTop: 2 },
  searchBox: {
    margin: 16,
    backgroundColor: AuthColors.white,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: AuthColors.text,
    borderWidth: 1,
    borderColor: AuthColors.border,
  },
  item: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    backgroundColor: AuthColors.white,
  },
  itemText: { fontSize: 15, color: AuthColors.text },
  itemSub: { fontSize: 12, color: AuthColors.textSecondary, marginTop: 2 },
  empty: { alignItems: 'center', paddingTop: 60 },
  emptyText: { color: AuthColors.textSecondary },
  loading: { alignItems: 'center', paddingTop: 60 },
  searchHint: { fontSize: 12, color: AuthColors.textSecondary, paddingHorizontal: 16, paddingBottom: 6 },
});
